name: AUR

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  aur:
    name: AUR

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: update
        run: node update.mjs

      - uses: KSXGitHub/github-actions-deploy-aur@v2.7.1
        if: ${{ steps.update.outputs.update == 'true' }}
        with:
          pkgname: defold
          pkgbuild: PKGBUILD
          updpkgsums: true
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: ${{ steps.update.outputs.version }}

      - uses: EndBug/add-and-commit@v9.1.4
        if: ${{ steps.update.outputs.update == 'true' }}
        with:
          add: "VERSION"
          message: ${{ format('{0}({1})', steps.update.outputs.version, steps.update.outputs.sha1) }}
          tag: ${{ steps.update.outputs.version }}
          default_author: github_actions
